apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudpulse-config
  namespace: prod

data:
  ENVIRONMENT: "prod"
  AI_SERVICE_URL: "http://cloudpulse-ai-service:8000"
  BACKEND_URL: "http://cloudpulse-backend:9090"
  