namespace: prod

frontend:
  replicaCount: 2
  image:
    tag: prod-14

backend:
  replicaCount: 2
  image:
    tag: prod-14

aiService:
  replicaCount: 2
  image:
    tag: prod-14

config:
  environment: prod

secret:
  appSecret: prod-secret-placeholder

hpa:
  backend:
    minReplicas: 2
    maxReplicas: 5

  aiService:
    minReplicas: 2
    maxReplicas: 5

ingress:
  host: "prod.4.247.242.122.nip.io"