namespace: prod
frontend:
  replicaCount: 2
  image:
    tag: prod-30
backend:
  replicaCount: 2
  image:
    tag: prod-30
aiService:
  replicaCount: 2
  image:
    tag: prod-30
config:
  environment: prod
secret:
  appSecret: prod-secret-placeholder
hpa:
  backend:
    minReplicas: 2
    maxReplicas: 5
  aiService:
    minReplicas: 2
    maxReplicas: 5
ingress:
  host: "prod.40.80.76.139.nip.io"
keyVault:
  secretName: cloudpulse-prod-app-secret
