{{- if .Values.hpa.backend.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: cloudpulse-backend-hpa
  namespace: {{ .Values.namespace }}

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.backend.name }}

  minReplicas: {{ .Values.hpa.backend.minReplicas }}
  maxReplicas: {{ .Values.hpa.backend.maxReplicas }}

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.backend.cpuUtilization }}
{{- end }}

---
{{- if .Values.hpa.aiService.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: cloudpulse-ai-service-hpa
  namespace: {{ .Values.namespace }}

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.aiService.name }}

  minReplicas: {{ .Values.hpa.aiService.minReplicas }}
  maxReplicas: {{ .Values.hpa.aiService.maxReplicas }}

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.aiService.cpuUtilization }}
{{- end }}