apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cloudpulse-keyvault-spc
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  secretObjects:
    - secretName: cloudpulse-secret
      type: Opaque
      data:
        - objectName: {{ .Values.keyVault.secretName }}
          key: APP_SECRET
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "56423576-14f8-4e09-9347-f7966abd320c"
    keyvaultName: "cloudpulse-kv"
    tenantId: "a45fe71a-f480-4e42-ad5e-aff33165aa35"
    objects: |
      array:
        - |
          objectName: {{ .Values.keyVault.secretName }}
          objectType: secret