apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudpulse-ai-service
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - dev
      - prod
  selector:
    matchLabels:
      app: cloudpulse-ai-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s