apiVersion: v1
kind: Service
metadata:
  name: cloudpulse-ai-service
  namespace: dev
  labels:
    app: cloudpulse-ai-service
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: cloudpulse-ai-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000