apiVersion: v1
kind: Service
metadata:
  name: cloudpulse-frontend
  namespace: dev
  labels:
    app: cloudpulse-frontend
    environment: dev
spec:
  type: LoadBalancer
  selector:
    app: cloudpulse-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80